### ISSUE TITLE
Error in checking hpfs status at mount /hpdevkit_vol/node1/contract_fs/mnt.

### ISSUE THREAD

**Issue by lathanbritz** [HotPocketDev/evernode-sdk#30] opened 2022-10-13 02:32 UTC
```
Lathans-iMac:mycontract lathan$ npm start

> mycontract@1.0.0 start
> npm run build && hpdevkit deploy dist


> mycontract@1.0.0 build
> npx ncc build src/mycontract.js -o dist

ncc: Version 0.34.0
ncc: Compiling file index.js into CJS
2980kB  dist/index.js
2980kB  [4002ms] - ncc 0.34.0
command: deploy (cluster: default)
sub-command: stop
hpdevkit_default_node_3
hpdevkit_default_node_2
hpdevkit_default_node_1
hpdevkit_default_node_5
hpdevkit_default_node_4
sub-command: sync
Applying hp.cfg overrides
Applying hp.cfg overrides
Applying hp.cfg overrides
Applying hp.cfg overrides
Applying hp.cfg overrides
sub-command: start
hpdevkit_default_node_4
hpdevkit_default_node_5
hpdevkit_default_node_3
hpdevkit_default_node_1
hpdevkit_default_node_2
Streaming logs of node 1:
sub-command: logs
20221013 02:29:41.158 [inf][hpc] Public key: ed70b730fd2d70f6559a8fc35f34a550f81fa7ddcdd73304375aa715324e86f496
20221013 02:29:41.158 [inf][hpc] Contract: d0e298cd-3cff-4572-b54c-7f5611af3837 (1.0)
20221013 02:29:41.181 [err][hpc] 2: Error in checking hpfs status at mount /hpdevkit_vol/node1/contract_fs/mnt.
20221013 02:29:41.181 [err][hpc] Couldn't initialize hpfs process at mount /hpdevkit_vol/node1/contract_fs/mnt.
20221013 02:29:41.198 [err][hpc] Contract file system initialization failed.
```

starting contract locks up often and i have to sit and restart and restart till it clears. what am i doing wrong or is there a better way i need to be doing this... also tried using hpdevkit clean but done not always resolve this.

**Comment by lathanbritz** [comment] 2022-10-13 02:48
I think the issue was the amount of resources i had given docker... upped those a bit to 2 CPU's and 10 Gig and seems to be more stable for the mean time will leave this ticket open and monitor for a bit.

**Comment by wojake** [comment] 2022-10-13 06:39
Happens to me often as well, probably something to do with the devkit than your server

**Comment by chalith** [comment] 2022-10-13 06:48
Then probably it should be from devkit, We'll investigate on this.

**Comment by chalith** [comment] 2022-10-13 07:56
@lathanbritz @wojake what are the platforms you are using? Windows or linux?

**Comment by lathanbritz** [comment] 2022-10-13 13:41
im on OS X, also figured out that im able many times to go in my docker interface and "kick the instance" click play and it fires up those stubborn instances that sometimes fail to restart.
<img width="1263" alt="Screen Shot 2022-10-13 at 10 38 45" src="https://user-images.githubusercontent.com/508629/195612462-e8702e3f-f74f-4344-a211-5e604c48bb27.png">


Been way better for me since providing more resources to docker! Error in checking hpfs status at mount is a thing of the past for me. Here are the settings im using in my local docker instance.

<img width="772" alt="Screen Shot 2022-10-13 at 10 40 25" src="https://user-images.githubusercontent.com/508629/195612882-94fcf659-9b92-4b87-8777-94b6d5b03414.png">

**Comment by wojake** [comment] 2022-10-13 15:07
Ubuntu, nothing on the OS since it's a fresh image to play around with the devkit.

**Comment by ravinsp** [comment] 2022-10-16 07:08
Closing due to the issue seems to be solved after docker resource adjustment.

**Comment by dangell7** [comment] 2022-10-22 21:10
OSX M1

**Comment by dangell7** [comment] 2022-10-22 21:14
I also receive this warning: 

`WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested`

When I run docker on my M1 I need to specify the platform. `docker build--platform=linux/amd64 ...`

**Comment by ravinsp** [comment] 2022-10-23 01:20
Thank you @dangell7 can you run the following commands on your terminal and let us know the results:
1. `docker run --rm -it evernodedev/hotpocket:latest-ubt.20.04-njs.16 version`
2. `docker run --rm -it --platform linux/amd64 evernodedev/hotpocket:latest-ubt.20.04-njs.16 version`

If this works, we'll have to update our devkit tooling to include this `--platform` parameter.

**Comment by dangell7** [comment] 2022-10-23 03:33
1.
```
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
0.6.0 
Ledger version: 0.5.0
```
2.
```
0.6.0 
Ledger version: 0.5.0
```

**Comment by ravinsp** [comment] 2022-10-23 03:54
@dangell7 Seems like in both cases it's working and only difference is the platform warning message.
If you're still getting `Error in checking hpfs status at mount` error, can you increase the resources allocated to Docker as @lathanbritz have done [here](https://github.com/HotPocketDev/evernode-sdk/issues/30#issuecomment-1277635145).

**Comment by dangell7** [comment] 2022-10-23 04:13
@ravinsp Agree, I realized after submitting that it's me who has to run that on the `build` command so that it's compatible with ubuntu. oof. 

I have 4 cores, 20 gigs and 2 gigs of swap. I don't think it's the allocation.

**Comment by ravinsp** [comment] 2022-10-23 04:45
@dangell7 is that the resources you have allocated just for Docker?

**Comment by dangell7** [comment] 2022-10-23 04:46
> @dangell7 is that the resources you have allocated just for Docker?

correct.

**Comment by dangell7** [comment] 2022-10-23 05:19
@ravinsp No issue on mac osx (intel) 2 cores, 8 gigs, 1 gb swap.

**Comment by ravinsp** [comment] 2022-10-23 05:37
@dangell7 so that means you don't have any mac-specific error anymore. The logs you see are normal operational logs of HotPocket. It means it's running as intended.

**Comment by dangell7** [comment] 2022-10-23 05:42
Thank you very much for the help.

**Closed** 2022-10-23 09:42 UTC

**Comment by dangell7** [comment] 2023-03-25 23:44
I still get this error from time to time on my M1 Mac.

**Comment by ravinsp** [comment] 2023-03-26 13:46
@dangell7 Maybe you are on the very edge of adequate system resources for running all your docker containers (not just hot pocket). Maybe try increasing the resources allocated to Docker?

**Comment by wojake** [comment] 2023-06-11 13:50
This issue should be re-opened. I couldn't get `hpdevkit` to run on my Mac

**Comment by develoQ** [comment] 2023-07-20 12:44
same error.
Docker resources: 5 core, 10GB mem
